### ISSUE TITLE
Should add a mention to dotnet org as well?

### ISSUE THREAD

**Issue by BethMassi** [Microsoft/microsoft.github.io#91]
@martinwoodward I didn't see the .NET Foundation org listed anywhere, but not sure where it would be classified, since it's a separate entity than MS.

**Comment by martinwoodward** [comment]
The .NET Foundation is deliberately not included because it is a separate non-profit.  There is heavily overlap because lots of projects in the .NET Foundation come from Microsoft but the .NET Foundation also has lots of OSS that comes from over clever folks such as Xamarin, Mono, ThinkTecture etc.

Maybe rather than including the organization in the data we should find a way to add a descriptive link to the .NET Foundation along with other OSS efforts Microsoft is heavily involved in.
